### PR TITLE
Fix several Qt deprecation warnings

### PR DESCRIPTION
**Pull request by sur5r**
`QString::null`, `QWheelEvent::pos` and `QWheelEvent::delta` are deprecated.

### CODE REVIEW

**Review by mboerwinkle — APPROVED** [review]
Looks good to me. Removed compiler errors without breaking anything on Archlinux/Qt5.15.2.

**Comment by sur5r** [comment]
Additional note: `QWheelEvent::position()` requires at least Qt 5.14. It might be wise to add a Qt version check to the cmake configuration.

**Comment by DeveloperPaul123** [comment]
Looks good to me thanks for the changes.

**Comment by Lenbok** [comment]
This commit breaks the ability to build fstl on Ubuntu 20.04 LTS, since only Qt 5.12 is available there.

**Pull request merged**
