### PR TITLE
Remove Legacy Qt Build Option

### PR DESCRIPTION
**Pull request by raptortech-js**
Master failed to build for me on NixOS; I tracked the issue down to `axis.cpp` not being built in the versions that had it, because it wasn't tracked in `fstl.pro`. I'm not entirely sure how it works to be honest, but at least for me, this patch gets it building.

### CODE REVIEW

**Comment by mboerwinkle** [comment]
Cool. Should we also take this opportunity to add in vector.h (used by loader.cpp)? My intuition tells me yes, but I know almost nothing about qt .pro files. I just noticed it was missing too, and wanted to say something.
Thanks,
Martin

**Comment by DeveloperPaul123** [comment]
Thanks for bringing this up. We haven't really been keeping the Qt creator build updated since CMake support was added. I can try to take a a look as well.

**Comment by raptortech-js** [comment]
I can also experiment with moving nixpkgs to use a CMake-based build, if you think that's the better choice long-term

**Comment by DeveloperPaul123** [comment]
Personally I think the CMake-based build is the best bet moving forward. I haven't used the Qt based build in some time and not sure if it's even needed anymore. 

@mkeeter Any reason to keep the `.pro` file around anymore since we have a CMake based build now?

**Comment by mkeeter** [comment]
Nope – CMake is definitely the wave of the future for Qt-based apps, so I'm fine removing the `.pro` file.

**Comment by DeveloperPaul123** [comment]
@raptortech-js If you update the PR to remove the `.pro` file, I'll happily merge it in.

**Comment by raptortech-js** [comment]
@DeveloperPaul123 Done, thanks!

**Comment by DeveloperPaul123** [comment]
Thanks @raptortech-js !

**Pull request merged**
