### PR TITLE
wait to load the stl file until file size  does not change anymore

### PR DESCRIPTION
**Pull request by gsohler**
fstl got issues when another tool rewrites the file while its beeing displayed.
fstl will reload too fast and does not display complete file.
ideally writing tool writes a tmp file and replaces with the real file in an atomic operation.

### CODE REVIEW

**Comment by lf94** [comment]
This would be fantastic to have merged in. It's an issue that blocks using many external tools proficiently.

**Comment by lf94** [comment]
Resolves https://github.com/fstl-app/fstl/issues/37

**Comment by DeveloperPaul123** [comment]
@gsohler @lf94 I made one small change since `unistd.h` is not available on windows. Let me know if it still works for you

**Comment by gsohler** [comment]
i tweaked your solution little bit to make it compile in linux again ...

**Comment by DeveloperPaul123** [comment]
Sorry about that @gsohler, I didn't have time to test on my Linux setup. If it's all good for you I'm happy to merge

**Comment by gsohler** [comment]
it works fine in my place. just tested again

**Comment by gsohler** [comment]
sur5r, cant see your change in 
https://github.com/sur5r/fstl/blob/master/src/window.cpp

**Comment by DeveloperPaul123** [comment]
> sur5r, cant see your change in https://github.com/sur5r/fstl/blob/master/src/window.cpp

Not sure if you saw, but he made a separate PR

**Comment by gsohler** [comment]
yes, is see now. sorry for looking close enough ... his PR still suggests usleep , tough ....

**Comment by DeveloperPaul123** [comment]
> yes, is see now. sorry for looking close enough ... his PR still suggests usleep , tough ....

Yes that's true, but apparently it's a Qt function https://doc.qt.io/qt-5/qthread.html#usleep
I missed that as well

**Pull request merged**
